# Chai 配置文件：五笔字型 98 版

schema:
  schema_id: wubi98
  name: 五笔字型 98 版
  version: "0.1"
  author:
    - 发明人 王永民
    - 重建人 蓝落萧 2320693692@qq.com
  description: |
    用于测试自动拆分

degenerator:
  - 笔画序列
  - 笔画拓扑

selector:
  - 笔顺优先
  - 根少优先
  - 能连不交、能散不连
  - 取大优先

classifier:
  1: [横, 提]
  2: [竖, 竖钩]
  3: [撇]
  4: [点, 捺]
  5: [横钩, 横撇, 横折, 横折钩, 横斜钩, 横折提, 横折折, 横折弯, 横撇弯钩, 横折弯钩, 横折折撇, 横折折折, 横折折折钩,
      竖提, 竖折, 竖弯, 竖弯钩, 竖折撇, 竖折折钩, 竖折折,
      撇点, 撇折, 弯钩, 斜钩]

mapper:
  g: [1, 王, 青上, 五, 夫, 夫上, 举下, 年下, 舛右]
  f: [土, 土变, 士, 二, 干, 十, 寸, 雨, 雨头, 甘, 未, 革下, 于下]
  d: [大, 犬, 戊, 三, 古, 石, 厂, 而上, 有上, 肆左, 其上]
  s: [木, 丁, 西, 杂下, 要上]
  a: [工, 戈, 七, 廿, 匚, 艹, 廾, 黄上, 寒中, 东上, 弋左, 牙上]
  h: [2, 目, 上, 卜, 止, 止变, 虍, 具上, 占上, 足下, 步下]
  j: [日, 曰, 早, 虫, 冒上, 师左, 横日, 齐下, 刂, 临左]
  k: [口, 流角, 川, 三竖]
  l: [田, 四竖, 囗, 甲, 车, 车旁, 四, 皿, 曾中, 罗上, 黑五]
  m: [山, 由, 贝, 骨上, 周外, 身框, 冂, 见二]
  t: [3, 禾, 竹头, 每上, 彳, 攵, 夂]
  r: [两撇, 白, 斤, 丘, 气, 手, 看上, 扌, 反外, 义下]
  e: [彡, 月, 青下, 且上, 用, 甬下, 力, 豕下, 采上, 毛, 豸, 衣下, 臼, 臼裂, 派角, 展底]
  w: [人, 亻, 八, 登头, 祭上, 几, 风外, 人改]
  q: [金, 钅, 鱼上, 儿, 勹, 犭二, 夕, 炙上, 久上, 角上, 鸟上, 见下, 抑中, 万下]
  y: [4, 言, 讠, 文, 方, 享上, 赢上, 亠, 隹右]
  u: [冬下, 冫, 总上, 前上, 前上离, 立, 辛, 辛变, 羊, 差上, 率右, 衤二, 北左, 丬, 爿, 六, 门, 舟下, 疒]
  i: [氵, 水, 聚下, 泰下, 鳏角, 脊外, 承外, 敝左, 小, 兴上, 尚上]
  o: [火, 灬, 业, 米, 广, 鹿外, 亦下, 变中, 兼下]
  p: [之, 冖, 宀, 辶, 衤三, 廴]
  n: [5, 已, 己, 巳, 官下, 假角, 候角, 声下, 尸, 心, 羽, 忄, 恭下]
  b: [粼右, 子, 了, 耳, 卩, 阝, 卷下, 也, 乃, 凵, 皮]
  v: [巛, 女, 刀, 九, 艮, 即左, 录上, 聿上, 彐]
  c: [又, 经角, 予上, 厶, 巴, 牛旁, 马上]
  x: [幺, 双折, 纟, 母, 彖上, 贯上, 弓, 匕, 化右, 比左]

aliaser:
  夫上: {source: 夫, indexList: [0, 1, 2]}
  年下: {source: 年, indexList: [2, ..., 5]}
  革下: {source: 革, indexList: [4, ..., 8]}
  于下: {source: 于, indexList: [1, 2]}
  其上: {source: 其, indexList: [0, ..., 5]}
  寒中: {source: 媾右, indexList: [0, ..., 4]}
  东上: {source: 东, indexList: [0, 1]}
  弋左: {source: 弋, indexList: [0, 1]}
  牙上: {source: 牙, indexList: [0, 1]}
  具上: {source: 具, indexList: [0, ..., 5]}
  三竖: {source: 带上, indexList: [1, 2, 3]}
  四竖: {source: 舞上, indexList: [3, ..., 6]}
  曾中: {source: 曾上, indexList: [2, ..., 7]}
  身框: {source: 身, indexList: [1, 2]}
  两撇: {source: 勿, indexList: [2, 3]}
  且上: {source: 且, indexList: [0, ..., 3]}
  豕下: {source: 豕, indexList: [1, ..., 6]}
  臼裂: {source: 舆框, indexList: [0, ..., 6]}
  展底: {source: 展内, indexList: [4, 5, 6]}
  久上: {source: 久, indexList: [0, 1]}
  见下: {source: 见, indexList: [2, 3]}
  鱼上: {source: 鱼, indexList: [0, ..., 6]}
  犭二: {source: 犭, indexList: [0, 1]}
  万下: {source: 万, indexList: [1, 2]}
  隹右: {source: 隹, indexList: [2, ..., 7]}
  羊变: {source: 羌, indexList: [0, ..., 5]}
  舟下: {source: 舟, indexList: [1, ..., 5]}
  脊外: {source: 脊上, indexList: [0, ..., 3]}
  承外: {source: 承, indexList: [5, 6, 7]}
  兴上: {source: 兴, indexList: [0, 1, 2]}
  亦下: {source: 亦, indexList: [2, ..., 5]}
  变中: {source: 变上, indexList: [2, ..., 5]}
  兼下: {source: 兼, indexList: [6, ..., 9]}
  录上: {source: 录, indexList: [0, 1, 2]}
  聿上: {source: 聿, indexList: [0, 1, 2]}
  经角: {source: 经右, indexList: [0, 1]}
  马上: {source: 马, indexList: [0, 1]}
  黑五: {source: 黑上, indexList: [0, 1, 2, 3, 4]}
  止变: {source: 足旁, indexList: [3, 4, 5, 6]}
  衤三: {source: 衤, indexList: [0, 1, 2]}
  衤二: {source: 衤, indexList: [3, 4]}
  见二: {source: 见, indexList: [0, 1]}
  土变: {source: 黑上, indexList: [5, 6, 7]}
  人改: {source: 内, indexList: [2, 3]}
  前上离: {source: 丧, indexList: [2, 3, 4]}
